### ISSUE TITLE
Project view add filter based on milestone

### ISSUE THREAD

**Issue by alexsapran** [zencrepes/zencrepes#124]
Hi, 

Thanks for this tool. I would like to ask if possible in the project view to add an option to filter with the milestones.

**Comment by Fgerthoffert** [comment]
Hey Alex,

Did you try through the issues view? You should be able to build that type of filter and get (mostly) the same data.

The challenge with adding a filter on Milestone is just that there is already one on labels, and dealing with filtering on two fields is not going to be fun. The best solution would be to add a facet mechanism, but then we would end up with something probably redundant with the issues view.

Can you take a look at achieving the same through the issue view and let me know what's missing?

I hope all is well otherwise ;)

**Comment by Fgerthoffert** [comment]
The issue view in the new version of ZenCrepes is addressing this. 

The previous version of ZenCrepes was having dedicated views for Milestones and Projects, but the underlying logic between the two was very similar.

The new version is taking a pretty different approach through a dedicated tab in the issues section and the support for duplicated filters for some fields (project, milestone and sprint).

So you can build your query (or keep it on the entire dataset), from there, select a project, and if the project has milestones, filter even more for a particular milestone.

The same applies for sprints with all possible combinations.

<img width="1908" alt="Screen Shot 2020-08-26 at 8 01 43 PM" src="https://user-images.githubusercontent.com/5667028/91368410-fbb23800-e7d6-11ea-84d4-353f59acc3d2.png">

So closing this issue for now ;)
